from . import credit_group
from . import letra
from . import letra_planilla
from . import letra_protesto
from . import letra_renovacion
from . import res_company
from . import res_partner
from . import account_move
from . import sale_order
from . import res_config_settings
